# Numpy Fundamentals

In [2]:
import numpy as np

x = np.array([20, 76, 10, 65])
print(x)
print(type(x))

[20 76 10 65]
<class 'numpy.ndarray'>


# Type Method

In [3]:
y = [20, 76, 10, 65]
print(y)
print(type(y))

[20, 76, 10, 65]
<class 'list'>


# Calculate the execution time

In [7]:
%timeit [j**4 for j in range(1, 111)]

9.94 µs ± 601 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
import numpy as np
%timeit np.arange(1, 111)**4

2.58 µs ± 268 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [14]:
import numpy as np
arr1 = [2, 56, 21, 90, 98]
x = np.array(arr1)
print(x)
x

[ 2 56 21 90 98]


array([ 2, 56, 21, 90, 98])

In [16]:
import numpy as np
arr1 = [2, 56, 21, 90, 98]
x = np.array(arr1)
print(type(x))
x

<class 'numpy.ndarray'>


array([ 2, 56, 21, 90, 98])

In [2]:
import numpy as np
l = []
for i in range(1, 5):
    data = int(input("Enter the number: "))
    l.append(data)
x = np.array(l)
print(x)

Enter the number:  12
Enter the number:  12
Enter the number:  12
Enter the number:  12


[12 12 12 12]


# Type of Array

# 0-D Array

In [23]:
import numpy as np
x = np.array(1)
print(x)
print("Dimension: ", x.ndim)

1
Dimension:  0


In [24]:
import numpy as np
x = np.array([1, 2, 3])
print(x)
print("Dimension: ", x.ndim)

[1 2 3]
Dimension:  1


In [34]:
import numpy as np
x = np.array([
    [1, 2, 3], 
    [11, 22, 33]
])
print(x)
print("Dimension: ", x.ndim)

[[ 1  2  3]
 [11 22 33]]
Dimension:  2


In [5]:
import numpy as np
x = np.array([[[1, 2, 3]]])
print(x)
print("Dimension: ", x.ndim)
print()

import numpy as np
x1 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]])
print(x1)
print("Dimension: ", x1.ndim)

[[[1 2 3]]]
Dimension:  3

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension:  3


In [4]:
import numpy as np

x = np.array([1,2,3], ndmin=3)
print(x)
print("Dimention: ",x.ndim)

[[[1 2 3]]]
Dimention:  3


# Array filled with 0's

In [13]:
import numpy as np
# 1D Array
zero_array = np.zeros(4)
print(zero_array)
# N-D Array
ndim_array = np.zeros((3,5))
print(ndim_array)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Array filled with 1's

In [11]:
import numpy as np
oneD_array = np.ones(5)
print(oneD_array)
print()
twoD_array = np.ones((2, 4))
print(twoD_array)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
import numpy as np
arr = np.array([3, 4, 5, 6])
print(arr)

[3 4 5 6]


# Empty Array

In [18]:
# Empty Array
import numpy as np
em_arr = np.empty(5)
print(em_arr)
print()
em_arr1 = np.empty((2, 4))
print(em_arr1)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Range 

In [21]:
import numpy as np
arange_arr = np.arange(5)
print(arange_arr)

arange_arr1 = np.arange(2, 11, 2)
print(arange_arr1)

[0 1 2 3 4]
[ 2  4  6  8 10]


# Diagonal

In [25]:
import numpy as np
dig_arr = np.eye(4)
print(dig_arr)
print()
dig_arr1 = np.eye(2, 5)
print(dig_arr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


# LinSpace

In [29]:
import numpy as np
lin_arr = np.linspace(0, 10, 5)
print(lin_arr)
print()
lin_arr1 = np.linspace(0, 1)
print(lin_arr1)
print()
lin_arr2 = np.linspace(0, 10, 5, dtype=int)
print(lin_arr2)


[ 0.   2.5  5.   7.5 10. ]

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]

[ 0  2  5  7 10]


# RANDOM Function

In [31]:
# Rand() Function
import numpy as np
var = np.random.rand(4)
print(var)
print()
var1 = np.random.rand(2, 4)
print(var1)

[0.53691702 0.91496153 0.29653724 0.56733088]

[[0.4057011  0.21706684 0.97349146 0.70839318]
 [0.96204189 0.586593   0.72953809 0.36210674]]


In [33]:
# Randn() Function
import numpy as np
var = np.random.randn(4)
print(var)
print()
var1 = np.random.randn(2, 4)
print(var1)

[0.92550327 0.80657283 0.69734078 0.90432725]

[[ 0.34489053 -0.26561271  1.00670469  0.40618966]
 [ 0.03653148 -1.68329622  0.64834344 -0.2226235 ]]


In [37]:
# Ranf() Function
import numpy as np
var_ranf = np.random.ranf(4)
print(var_ranf)
print()
var_ranf1 = np.random.ranf((2, 4))
print(var_ranf1)

[2.42335759e-02 4.54398806e-01 3.77739011e-04 4.59267026e-01]

[[0.19081291 0.70217606 0.11509741 0.85899152]
 [0.25972882 0.20906406 0.70476534 0.76183282]]


In [46]:
# Rabdint() Function
import numpy as np
var = np.random.randint(10)
print(var)

var1 = np.random.randint(10, 20)
print(var1)

var3 = np.random.randint(10, 20, 3)
print(var3)

var4 = np.random.randint(10, 20, (3,2))
print(var4)

5
15
[10 15 16]
[[12 18]
 [11 15]
 [19 16]]


# DATA TYPE IN NUMPY ARRAY

In [6]:
# Boolean
import numpy as np
x = np.array([True, False, False, True, True])
print(x)
print(x.dtype)

[ True False False  True  True]
bool


In [5]:
# Integer
import numpy as np
x = np.array([2, 4, 6, 8, 10])
print(x)
print(x.dtype)

[ 2  4  6  8 10]
int32


In [12]:
# string
import numpy as np
x = np.array(["Arshad", "Gauhar", "Aatif"])
print(x)
print(x.dtype)

['Arshad' 'Gauhar' 'Aatif']
<U6


In [14]:
# Complex
import numpy as np
x = np.array([3+4j, 5+6j, 6])
print(x)
print(x.dtype)

[3.+4.j 5.+6.j 6.+0.j]
complex128


In [16]:
# Float
import numpy as np
x = np.array([2.44, 5.66, 7])
print(x)
print(x.dtype)

[2.44 5.66 7.  ]
float64


In [19]:
# ✨ Specify the Data Type While Creating an Array
import numpy as np
x = np.array([2.44, 5.66, 7], dtype=int)
print(x)
print("Data Type:",x.dtype)

[2 5 7]
Data Type: int32


In [25]:
import numpy as np
x = np.array([3, 5, 7, 9], dtype=float)
print(x)
print("Data Type:",x.dtype)

import numpy as np
x1 = np.array([3, 5, 7, 9], dtype="f")
print(x1)
print("Data Type:",x1.dtype)

[3. 5. 7. 9.]
Data Type: float64
[3. 5. 7. 9.]
Data Type: float32


# How to use data type as a function

x = np.array([2, 4, 6, 8])
new = np.float32(x)
print(x)
print(new)
print(x.dtype)
print(new.dtype)

# ✨ astype() Function in NumPy# ✨ astype() Function in NumPy

In [32]:
x1 = np.array([2, 4, 6, 8])
new1 = x.astype(float)
print(x1)
print(new1)
print(x1.dtype)
print(new1.dtype)


[2 4 6 8]
[2. 4. 6. 8.]
int32
float64


# Arithmatic Operation in NumPy Array   1-D Array

# Addition

In [34]:
import numpy as np
var1 = np.array([2, 4, 6, 8])
var2 = var1 + 10
print("var1:", var1)
print("var2:", var2)

var1: [2 4 6 8]
var2: [12 14 16 18]


In [38]:
import numpy as np
var3 = np.array([2, 4, 6, 8])
var4 = np.array([10, 10, 10, 10])
sum_res = var3 + var4
print("Addition:", sum_res)

Addition: [12 14 16 18]


In [58]:
# Add Function
import numpy as np
var1 = np.array([2, 4, 6, 8])
# var2 = np.array([2, 4, 6, 8])
# res_var = np.add(var1, var2)
res_var = np.add(var1, 5)
print("res_var:", res_var)


res_var: [ 7  9 11 13]


# Substraction

In [39]:
import numpy as np
var1 = np.array([20, 40, 60, 80])
var_res = var1 - 10
print("var_res:", var_res)

var_res: [10 30 50 70]


In [40]:
import numpy as np
var3 = np.array([20, 40, 60, 80])
var4 = np.array([10, 20, 30, 40])
sub_res = var3 - var4
print("Subtraction:", sub_res)

Subtraction: [10 20 30 40]


# Multiplication

In [44]:
import numpy as np
var1 = np.array([20, 40, 60, 80])
mul_res = var1 * 10
print("Multiplication:", mul_res)

Multiplication: [200 400 600 800]


In [43]:
import numpy as np
var3 = np.array([20, 40, 60, 80])
var4 = np.array([10, 20, 30, 40])
mul_res = var3 * var4
print("Multiplication:", mul_res)

Multiplication: [ 200  800 1800 3200]


# Division

In [46]:
import numpy as np
var1 = np.array([20, 40, 60, 80])
div_res = var1 / 10
print("Division:", div_res)

Division: [2. 4. 6. 8.]


In [47]:
import numpy as np
var3 = np.array([20, 40, 60, 80])
var4 = np.array([10, 20, 30, 40])
div_res = var3 / var4
print("Division:", div_res)

Division: [2. 2. 2. 2.]


# Modulus

In [48]:
import numpy as np
var1 = np.array([22, 44, 66, 88])
mod_res = var1 % 10
print("Modulus:", mod_res)

Modulus: [2 4 6 8]


In [49]:
import numpy as np
var3 = np.array([23, 42, 61, 85])
var4 = np.array([10, 20, 30, 40])
mod_res = var3 % var4
print("Modulus:", mod_res)

Modulus: [3 2 1 5]


# Exponential (Power)

In [50]:
import numpy as np
var1 = np.array([2, 4, 6, 8])
exp_res = var1 ** 2
print("Exponential:", exp_res)

Exponential: [ 4 16 36 64]


In [59]:
import numpy as np
var1 = np.array([10, 20, 30, 40])
var2 = np.array([2, 2, 2, 2])
exp_res = var1 ** var2
print("Exponential:", exp_res)

Exponential: [ 100  400  900 1600]


# Reciprocal (1/a)

In [60]:
import numpy as np
var1 = np.array([2, 4, 6, 8])
rec_res = 1/var1 
print("Reciprokal:", rec_res)

Reciprokal: [0.5        0.25       0.16666667 0.125     ]


In [62]:
import numpy as np
var1 = np.array([2, 4, 6, 8])
rec_res = np.reciprocal(var1)
print("Reciprokal:", rec_res)

Reciprokal: [0 0 0 0]


# Arithmatic Operation in NumPy Array   2-D Array

# Addition

In [64]:
import numpy as np
var1 = np.array([[2, 4, 6, 8],
                 [3, 5, 7, 9]])
var2 = np.array([[10, 10, 10, 10],
                 [2, 4, 6, 8]])
sum_res = var1 + var2
print(sum_res)

[[12 14 16 18]
 [ 5  9 13 17]]


# Subtraction

In [65]:
import numpy as np
var1 = np.array([[2, 4, 6, 8],
                 [3, 5, 7, 9]])
var2 = np.array([[1, 1, 1, 1],
                 [2, 4, 6, 8]])
sub_res = var1 - var2
print(sub_res)

[[1 3 5 7]
 [1 1 1 1]]


# Multiplication

In [66]:
import numpy as np
var1 = np.array([[2, 4, 6, 8],
                 [3, 5, 7, 9]])
var2 = np.array([[1, 1, 1, 1],
                 [2, 4, 6, 8]])
mul_res = var1 * var2
print(mul_res)

[[ 2  4  6  8]
 [ 6 20 42 72]]


# Division

In [67]:
import numpy as np
var1 = np.array([[2, 4, 6, 8],
                 [3, 5, 7, 9]])
var2 = np.array([[1, 1, 1, 1],
                 [2, 4, 6, 8]])
div_res = var1 / var2
print(div_res)

[[2.         4.         6.         8.        ]
 [1.5        1.25       1.16666667 1.125     ]]


# Modulus

In [68]:
import numpy as np
var1 = np.array([[2, 4, 6, 8],
                 [3, 5, 7, 9]])
var2 = np.array([[1, 1, 1, 1],
                 [2, 4, 6, 8]])
mod_res = var1 % var2
print(mod_res)

[[0 0 0 0]
 [1 1 1 1]]


# Exponentional

In [69]:
import numpy as np
var1 = np.array([[2, 4, 6, 8],
                 [3, 5, 7, 9]])
var2 = np.array([[1, 1, 1, 1],
                 [2, 4, 6, 8]])
exp_res = var1 ** var2
print(exp_res)

[[       2        4        6        8]
 [       9      625   117649 43046721]]


# ARITHMATIC FUNCTION IN NUMPY ARRAY

# Min & Max

In [4]:
import numpy as np
var = np.array([13, 6, 9, 12])
print("Minimum:",np.min(var))
print("Maximum:",np.max(var))

Minimum: 6
Maximum: 13


# Position of Min & Max

In [8]:
import numpy as np
var = np.array([13, 60, 9, 1])
print("Position of Minimum:",np.argmin(var))
print("Position of Maximum:",np.argmax(var))

Position of Minimum: 3
Position of Maximum: 1


# 2D Array
# Min & Max and Position of Min & Max

In [19]:
import numpy as np
var1 = np.array([
    [13, 20, 119, 10],
    [40, 10, 30, 1],
    [14, 12, 32, 0]])
print(var1)
print("Minimum:", np.min(var1, axis=0))
print("Maximum:", np.max(var1, axis=0))

[[ 13  20 119  10]
 [ 40  10  30   1]
 [ 14  12  32   0]]
Minimum: [13 10 30  0]
Maximum: [ 40  20 119  10]


In [22]:
# If not pass axis?
import numpy as np
var1 = np.array([
    [13, 20, 119, 10],
    [40, 10, 30, 1]])
print(var1)
print("Minimum:", np.min(var1), "Position:", np.argmin(var1))
print("Maximum:", np.max(var1), "Position:", np.argmax(var1))

[[ 13  20 119  10]
 [ 40  10  30   1]]
Minimum: 1 Position: 7
Maximum: 119 Position: 2


# SQRT function

In [27]:
import numpy as np
var1 = np.array([
    [16, 25, 121],
    [48, 9, 10]])
print(var1)
print("Square Root:")
print(np.sqrt(var1))

[[ 16  25 121]
 [ 48   9  10]]
Square Root:
[[ 4.          5.         11.        ]
 [ 6.92820323  3.          3.16227766]]


# SIN function

In [31]:
import numpy as np
var1 = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print("Value of sin:")
print(np.sin(var1))

Value of sin:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


# COS function

In [33]:
import numpy as np
var1 = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print("Value of cos:")
print(np.cos(var1))

Value of cos:
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


# CUMSUM function  1D Array

In [35]:
import numpy as np
var1 = np.array([1, 2, 3, 5, 7])
print("Value of cumulative sum:",np.cumsum(var1))

Value of cumulative sum: [ 1  3  6 11 18]


# CUMSUM function  2D Array (Row wise Axis=1)

In [36]:
import numpy as np
var1 = np.array([
    [1, 2, 3],
    [5, 7, 8]])
print("Value of cumulative sum:",np.cumsum(var1))

Value of cumulative sum: [ 1  3  6 11 18 26]


# CUMSUM function  2D Array (With Axis)

In [39]:
import numpy as np
var1 = np.array([
    [1, 2, 3],
    [5, 7, 8]])
print("Value of cumulative sum:")
print(np.cumsum(var1, axis=1))

Value of cumulative sum:
[[ 1  3  6]
 [ 5 12 20]]


# CUMSUM function  2D Array (Column wise Axis=0)

In [42]:
import numpy as np
var1 = np.array([
    [1, 2, 3],
    [5, 7, 8],
    [2, 3, 4]])
print("Value of cumulative sum:")
print(np.cumsum(var1, axis=0))

Value of cumulative sum:
[[ 1  2  3]
 [ 6  9 11]
 [ 8 12 15]]


#SHAPE & RESHAPING

# SHAPE & RE-SHAPE

In [6]:
import numpy as np
var = np.array([[1,2,3], [1,2,3]])
print(var)
print(var.ndim)
print("Shape:",var.shape)

[[1 2 3]
 [1 2 3]]
2
Shape: (2, 3)


In [27]:
import numpy as np
var = np.array([1,2,3], ndmin=6)
print(var)
print(var.ndim)
print("Shape:",var.shape)

[[[[[[1 2 3]]]]]]
6
Shape: (1, 1, 1, 1, 1, 3)


# How to Convert 1-D Array into N-D Array 

In [50]:
# How to Convert 1-D Array into 2-D Array 
import numpy as np
var = np.array([2, 3, 4, 5, 6, 7, 8, 9, 1])
print(var)
print("Dimention: ", var.ndim)
print("Shape:", var.shape)

reshape_var = var.reshape(3, 3)
print(reshape_var)
print("Dimention: ", reshape_var.ndim)
print("Shape:", reshape_var.shape)

[2 3 4 5 6 7 8 9 1]
Dimention:  1
Shape: (9,)
[[2 3 4]
 [5 6 7]
 [8 9 1]]
Dimention:  2
Shape: (3, 3)


In [1]:
# How to Convert 1-D Array into 3-D Array 
import numpy as np
var = np.array([2, 3, 4, 5, 6, 7, 8, 9, 1])
print(var)
print("Dimention: ", var.ndim)
print("Shape:", var.shape)

reshape_var = var.reshape(3, 1, 3)
print(reshape_var)
print("Dimention: ", reshape_var.ndim)
print("Shape:", reshape_var.shape)

# Convert 3-D array into 1-D array
one = reshape_var.reshape(-1)
print(one)
print("Dimention: ", one.ndim)
print("Shape:", one.shape)

[2 3 4 5 6 7 8 9 1]
Dimention:  1
Shape: (9,)
[[[2 3 4]]

 [[5 6 7]]

 [[8 9 1]]]
Dimention:  3
Shape: (3, 1, 3)
[2 3 4 5 6 7 8 9 1]
Dimention:  1
Shape: (9,)


# BROAD CASTING IN  NUMPY ARRAY

In [2]:
import numpy as np
var1 = np.array([1, 2, 3])
var2 = np.array([[1], 
                 [2],
                 [3]])

var3 = var1+ var2
print(var3)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


INDEXING

# INDEXING

In [13]:
# Create Numpy Array  - 1D
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

# Access the element of the array
first_element = arr1[0]
last_element = arr1[-1]
print("First Element:",first_element)
print("Last Element:",last_element)

[10 20 30 40 50]
First Element: 10
Last Element: 50


In [29]:
# Create Numpy Array  -  2D
import numpy as np
arr2 = np.array([[10, 20, 30],
                 [34, 40, 50]])
print(arr2)
print("Dimension:",arr2.ndim)
print("Shape:",arr2.shape)

# Access the element of the array
fir_row = arr2[0,-1]
sec_row = arr2[1, 0]
print("first row:",fir_row)
print("Sec row:",sec_row)

[[10 20 30]
 [34 40 50]]
Dimension: 2
Shape: (2, 3)
first row: 30
Sec row: 34


In [41]:
# Create Numpy Array  -  3D
import numpy as np
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(arr3)
print("Dimension:",arr3.ndim)
print("Shape:",arr3.shape)

# Access the element of the array
# Target= 40
fir_row_element = arr3[0,1,1]

# Target= 3
sec_row_element = arr3[1, 0, -1]
print("First row Element:",fir_row_element)
print("Sec row Element:",sec_row_element)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension: 3
Shape: (2, 2, 3)
First row Element: 5
Sec row Element: 9


# SLICING

In [61]:
# 1-D ARRAY
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print("Dimension:",arr1.ndim)
print("Shape:",arr1.shape)

fetch_2_to_5_element = arr1[1:5:1]
print("Fetch 2 to 5 elments:", fetch_2_to_5_element)


# Slicing with Start Only
fetch_all_from_3 = arr1[2:]
print("3 to all:", fetch_all_from_3)

# Slicing with Stop Only
stop_on_4 = arr1[:4]
print("stop on 4:", stop_on_4)


# Slicing the entire array
entire_array = arr1[:]
print("Entire Array:", entire_array)

# Slicing with steps
alternate_elements = arr1[::2]
print("Alternate Elements:", alternate_elements)

# Negetive slicing
negetive_slicing = arr1[-4:-1]
print("Negetive Slicing:", negetive_slicing)

# Reverse Array
reverse_array = arr1[::-1]
print("Reverse Array:", reverse_array)

[1 2 3 4 5]
Dimension: 1
Shape: (5,)
Fetch 2 to 5 elments: [2 3 4 5]
3 to all: [3 4 5]
stop on 4: [1 2 3 4]
Entire Array: [1 2 3 4 5]
Alternate Elements: [1 3 5]
Negetive Slicing: [2 3 4]
Reverse Array: [5 4 3 2 1]


In [78]:
# Create Numpy Array  -  2D
import numpy as np
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                [70, 80, 90]])
print(arr2)
print("Dimension:",arr2.ndim)
print("Shape:",arr2.shape)

# Get the First Row
first_row = arr2[0, :]
print("First Row:", first_row)

# Get the Specific element of second Row
sec_arr_elements = arr2[1, 1:3]
print("Second Array Elements:", sec_arr_elements)

# Get the First Column
last_column = arr2[:, 2]
print("Last Column:", last_column)

# Get the Specific element of third Columns
sec_third_col_elements = arr2[1:3, 2:3]
print("Second Third Specific Elements:", sec_third_col_elements)

# Get a Subarray
sub_array_50_60_70_80 = arr2[0:3, 1:3]
print("Sub Array:", sub_array_50_60_70_80)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension: 2
Shape: (3, 3)
First Row: [10 20 30]
Second Array Elements: [50 60]
Last Column: [30 60 90]
SEcond Third Specific Elements: [[60]
 [90]]
Sub Array: [[20 30]
 [50 60]
 [80 90]]


ITERATION IN NUMPY ARRAY

In [8]:
# 1D Array
import numpy as np
arr_1D = np.array([2, 3, 4, 5])
print(arr_1D)
for i in arr_1D:
    print(i)
for i in range(len(arr_1D)):
    print(arr_1D[i])

[2 3 4 5]
2
3
4
5
2
3
4
5


In [13]:
# 2D Array (Row by Row)
import numpy as np
arr_2D = np.array(
    [
        [2, 3, 4, 5],
        [7, 9, 11, 13]
    ]
)
print(arr_2D)
print("Dimension:", arr_2D.ndim, "| Shape:", arr_2D.shape)
for i in arr_2D:
    print(i)


[[ 2  3  4  5]
 [ 7  9 11 13]]
Dimension: 2 | Shape: (2, 4)
[2 3 4 5]
[ 7  9 11 13]


In [14]:
# 2D Array (Element by Element)
import numpy as np
arr_2D = np.array(
    [
        [2, 3, 4, 5],
        [7, 9, 11, 13]
    ]
)
print(arr_2D)
print("Dimension:", arr_2D.ndim, "| Shape:", arr_2D.shape)
for i in arr_2D:
    for j in i:
        print(j)


[[ 2  3  4  5]
 [ 7  9 11 13]]
Dimension: 2 | Shape: (2, 4)
2
3
4
5
7
9
11
13


In [16]:
# 3D Array (Row by Row)
import numpy as np
arr_3D = np.array(
    [
        [
            [2, 3, 4, 5],
            [7, 9, 11, 13]
        ],
        [
            [12, 13, 14, 15],
            [7, 9, 11, 13]
        ],
    ]       
)
print(arr_3D)
print("Dimension:", arr_3D.ndim, "| Shape:", arr_3D.shape)
for i in arr_3D:
    print(i)

[[[ 2  3  4  5]
  [ 7  9 11 13]]

 [[12 13 14 15]
  [ 7  9 11 13]]]
Dimension: 3 | Shape: (2, 2, 4)
[[ 2  3  4  5]
 [ 7  9 11 13]]
[[12 13 14 15]
 [ 7  9 11 13]]


In [18]:
# 3D Array (Element by Element)
import numpy as np
arr_3D = np.array(
    [
        [
            [2, 3, 4, 5],
            [7, 9, 11, 13]
        ],
        [
            [12, 13, 14, 15],
            [7, 9, 11, 13]
        ],
    ]       
)
print(arr_3D)
print("Dimension:", arr_3D.ndim, "| Shape:", arr_3D.shape)
for i in arr_3D:
    for j in i:
        for k in j:
            print(k)

[[[ 2  3  4  5]
  [ 7  9 11 13]]

 [[12 13 14 15]
  [ 7  9 11 13]]]
Dimension: 3 | Shape: (2, 2, 4)
2
3
4
5
7
9
11
13
12
13
14
15
7
9
11
13


# NDITER() Method for iteration

In [21]:
# Iteration in 1-D Array (nditer() method)
import numpy as np
arr_1D = np.array([2, 3, 4, 5])
print(arr_1D)
print("Dimension:", arr_1D.ndim, "| Shape:", arr_1D.shape)
for i in np.nditer(arr_1D):
    print(i)

[2 3 4 5]
Dimension: 1 | Shape: (4,)
2
3
4
5


In [22]:
# Iteration in 2-D Array (nditer() method)
import numpy as np
arr_2D = np.array(
    [
        [2, 3, 4, 5],
        [7, 9, 11, 13]
    ]
)
print(arr_2D)
print("Dimension:", arr_2D.ndim, "| Shape:", arr_2D.shape)
for i in np.nditer(arr_2D):
    print(i)

[[ 2  3  4  5]
 [ 7  9 11 13]]
Dimension: 2 | Shape: (2, 4)
2
3
4
5
7
9
11
13


In [26]:
# Iteration in 2-D Array (nditer() method)
import numpy as np
arr_3D = np.array(
    [
        [
            [2, 3, 4, 5],
            [7, 9, 11, 13]
        ],
        [
            [12, 13, 14, 15],
            [7, 9, 11, 13]
        ],
    ]
)
print(arr_3D)
print("Dimension:", arr_3D.ndim, "| Shape:", arr_3D.shape)
for i in np.nditer(arr_3D):
    print(i)

[[[ 2  3  4  5]
  [ 7  9 11 13]]

 [[12 13 14 15]
  [ 7  9 11 13]]]
Dimension: 3 | Shape: (2, 2, 4)
2
3
4
5
7
9
11
13
12
13
14
15
7
9
11
13


# Convert the data type during iteration using buffered and op_dtypes methods


In [28]:
# Integer -> String
import numpy as np
arr_2D = np.array(
    [
        [2, 3, 4, 5],
        [7, 9, 11, 13]
    ]
)
print(arr_2D)
print("Dimension:", arr_2D.ndim, "| Shape:", arr_2D.shape)
for i in np.nditer(arr_2D, flags=['buffered'], op_dtypes=["S"]):
    print(i)

[[ 2  3  4  5]
 [ 7  9 11 13]]
Dimension: 2 | Shape: (2, 4)
b'2'
b'3'
b'4'
b'5'
b'7'
b'9'
b'11'
b'13'


In [31]:
# Integer -> Float
import numpy as np
arr_2D = np.array(
    [
        [2, 3, 4, 5],
        [7, 9, 11, 13]
    ]
)
print(arr_2D)
print("Dimension:", arr_2D.ndim, "| Shape:", arr_2D.shape)
for i in np.nditer(arr_2D, flags=['buffered'], op_dtypes=["float"]):
    print(i)

[[ 2  3  4  5]
 [ 7  9 11 13]]
Dimension: 2 | Shape: (2, 4)
2.0
3.0
4.0
5.0
7.0
9.0
11.0
13.0


# NDENUMERATE() METHOD

In [33]:
# Iteration in 1-D Array (ndenumerate() method)
import numpy as np
arr_1D = np.array([2, 3, 4, 5])
print(arr_1D)
print("Dimension:", arr_1D.ndim, "| Shape:", arr_1D.shape)
for index, num in np.ndenumerate(arr_1D):
    print(index, num)

[2 3 4 5]
Dimension: 1 | Shape: (4,)
(0,) 2
(1,) 3
(2,) 4
(3,) 5


In [35]:
# Iteration in 2-D Array (ndenumerate() method)
import numpy as np
arr_2D = np.array([
    [2, 3, 4],
    [12, 23, 45]
])
print(arr_2D)
print("Dimension:", arr_2D.ndim, "| Shape:", arr_2D.shape)
for index, num in np.ndenumerate(arr_2D):
    print(index, num)

[[ 2  3  4]
 [12 23 45]]
Dimension: 2 | Shape: (2, 3)
(0, 0) 2
(0, 1) 3
(0, 2) 4
(1, 0) 12
(1, 1) 23
(1, 2) 45


In [36]:
# Iteration in 3-D Array (ndenumerate() method)
import numpy as np
arr_3D = np.array(
    [
        [
            [2, 3, 4, 5],
            [7, 9, 11, 13]
        ],
        [
            [12, 13, 14, 15],
            [7, 9, 11, 13]
        ],
    ]
)
print(arr_3D)
print("Dimension:", arr_3D.ndim, "| Shape:", arr_3D.shape)
for index, num in np.ndenumerate(arr_3D):
    print(index, num)

[[[ 2  3  4  5]
  [ 7  9 11 13]]

 [[12 13 14 15]
  [ 7  9 11 13]]]
Dimension: 3 | Shape: (2, 2, 4)
(0, 0, 0) 2
(0, 0, 1) 3
(0, 0, 2) 4
(0, 0, 3) 5
(0, 1, 0) 7
(0, 1, 1) 9
(0, 1, 2) 11
(0, 1, 3) 13
(1, 0, 0) 12
(1, 0, 1) 13
(1, 0, 2) 14
(1, 0, 3) 15
(1, 1, 0) 7
(1, 1, 1) 9
(1, 1, 2) 11
(1, 1, 3) 13


# COPY VS VIEW FUNCTIONS

In [38]:
# COPY
import numpy as np
original_arr = np.array([1, 2, 3, 4])
copy = original_arr.copy()
copy[0] = 100
print("Original Array: ",original_arr)
print("Copy:",copy)

Original Array:  [1 2 3 4]
Copy: [100   2   3   4]


In [39]:
# VIEW
import numpy as np
original_arr = np.array([1, 2, 3, 4])
copy = original_arr.view()
copy[0] = 100
print("Original Array: ",original_arr)
print("Copy:",copy)

Original Array:  [100   2   3   4]
Copy: [100   2   3   4]


How to Check Whether Memory is Shared using Base method

In [40]:
# COPY
import numpy as np
original_arr = np.array([1, 2, 3, 4])
copy = original_arr.copy()
print(original_arr.base)
# None means copy variable has its own memory

None


In [42]:
# VIEW
import numpy as np
original_arr = np.array([1, 2, 3, 4])
copy = original_arr.view()
print(copy.base)
# [1 2 3 4]  means copy variable using the memory of the original_arr

[1 2 3 4]


# JOINING & SPLIT NUMPY ARRAY

# 1. JOINING

In [10]:
# 1. CONCATENATE FUNCTION

# Joining in 1D Array
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1)
arr2 = np.array([5, 6, 7, 8])
print(arr2)
new_arr = np.concatenate((arr1, arr2))
print(new_arr)
print()



[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]



In [19]:
# Joining in 2D Array (Column wise, axis=0)
print("----------- 2D Array (Column wise) ---------------")
import numpy as np
arr1 = np.array(
    [
        [1, 2], 
        [3, 4]
    ]
)
print(arr1)
print("Dimension:",arr1.ndim)
print()
arr2 = np.array(
    [
        [11, 12], 
        [13, 14]
    ]
)
print(arr2)
print("Dimension:",arr2.ndim)
print()
new_arr = np.concatenate((arr1, arr2), axis=0)
print(new_arr)
print("Dimension:",new_arr.ndim)
print()

# Joining in 2D Array (Row wise, axis=1)
print("-------------> 2D ARRAY (Row Wise)-------------")
arr3 = np.array(
    [
        [1, 2], 
        [3, 4]
    ]
)
print(arr3)
print("Dimension:",arr3.ndim)
print()
arr4 = np.array(
    [
        [11, 12], 
        [13, 14]
    ]
)
print(arr4)
print("Dimension:",arr4.ndim)
print()
new_arr1 = np.concatenate((arr3, arr4), axis=1)
print(new_arr1)
print("Dimension:",new_arr1.ndim)

----------- 2D Array (Column wise) ---------------
[[1 2]
 [3 4]]
Dimension: 2

[[11 12]
 [13 14]]
Dimension: 2

[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]
Dimension: 2

-------------> 2D ARRAY (Row Wise)-------------
[[1 2]
 [3 4]]
Dimension: 2

[[11 12]
 [13 14]]
Dimension: 2

[[ 1  2 11 12]
 [ 3  4 13 14]]
Dimension: 2


# 2. STACK FUNCTION

In [26]:
# Joining in 1D Array
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print("Dimension:",arr1.ndim)

arr2 = np.array([5, 6, 7, 8])
print(arr2)
print("Dimension:",arr1.ndim)

new_arr = np.stack((arr1, arr2), axis=1)
print(new_arr)
print("Dimension:",new_arr.ndim)
print()


[1 2 3 4]
Dimension: 1
[5 6 7 8]
Dimension: 1
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Dimension: 2



# 3. HSTACK FUNCTION

In [23]:

# Joining in 1D Array
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print("Dimension:",arr1.ndim)

arr2 = np.array([5, 6, 7, 8])
print(arr2)
print("Dimension:",arr1.ndim)

new_arr = np.hstack((arr1, arr2))
print(new_arr)
print("Dimension:",new_arr.ndim)
print()

[1 2 3 4]
Dimension: 1
[5 6 7 8]
Dimension: 1
[1 2 3 4 5 6 7 8]
Dimension: 1



# 4. VSTACK FUNCTION

In [27]:

# Joining in 1D Array
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print("Dimension:",arr1.ndim)

arr2 = np.array([5, 6, 7, 8])
print(arr2)
print("Dimension:",arr1.ndim)

new_arr = np.vstack((arr1, arr2))
print(new_arr)
print("Dimension:",new_arr.ndim)
print()

[1 2 3 4]
Dimension: 1
[5 6 7 8]
Dimension: 1
[[1 2 3 4]
 [5 6 7 8]]
Dimension: 2



# 5. SPLIT


In [34]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr1)
print()
split_arr = np.split(arr1, 3)
print(split_arr)
print(split_arr[0])




[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]


# 6. ARRAY_SPLIT

In [38]:
# 1D Array
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr1)
print()
split_arr = np.array_split(arr1, 4)
print(split_arr)
print()

# 2D Array
import numpy as np

arr2d = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
print(arr2d)
print()
split_arr2d = np.array_split(arr2d, 4)
print(split_arr2d)

[1 2 3 4 5 6 7]

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]

[[1 2 3]
 [4 5 6]]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32)]


# SEARCHING

# Where Function

In [10]:
# 1D Numpy Array
import numpy as np
arr = np.array([1, 2, 3, 4, 4, 7, 4, 2, 1, 3])
print(arr)
result = np.where(arr == 4)
print("4 is available at index :", result)

# Find the even number index
even = np.where(arr % 2 == 0)
print("Index of even number:", even)

# Find the odd number index
odd = np.where(arr % 2 != 0)
print("Index of odd number:", odd)

# Find the greater than 3 numbers index
greater_than_2 = np.where(arr > 3)
print("Index of greater than 2 :", greater_than_2)

[1 2 3 4 4 7 4 2 1 3]
4 is available at index : (array([3, 4, 6], dtype=int64),)
Index of even number: (array([1, 3, 4, 6, 7], dtype=int64),)
Index of odd number: (array([0, 2, 5, 8, 9], dtype=int64),)
Index of greater than 2 : (array([3, 4, 5, 6], dtype=int64),)


In [19]:
# 2-D Numpy Array
import numpy as np
arr2d = np.array(
    [
        [1, 2, 3, 4],
        [4, 7, 4, 2]
    ]
)
print(arr2d)
print("Dimension:",arr2d.ndim)
result = np.where(arr2d == 2)
print("4 is available at index :", result)

# Access the row , columns seperately

row, col = np.where(arr == 4)
print("Row:", row)
print("Column:", col)


[[1 2 3 4]
 [4 7 4 2]]
Dimension: 2
4 is available at index : (array([0, 1], dtype=int64), array([1, 3], dtype=int64))
Row: [0 1 1]
Column: [3 0 2]


In [23]:
# Search Sorted Array

import numpy as np
arr = np.array([4, 2, 13, 5])
print(arr)
result = np.searchsorted(arr, 3)
print("4 should insert at:", result, "index")

[ 4  2 13  5]
4 should insert at: 2 index


In [31]:
# Use of side 
import numpy as np
arr = np.array([10, 20, 20, 20, 30])
print(arr)
result = np.searchsorted(arr, 20)
print("20 should insert at:", result, "index")

result1 = np.searchsorted(arr, 20, side="right")
print("20 should insert at:", result1, "index")

[10 20 20 20 30]
20 should insert at: 1 index
20 should insert at: 4 index


In [33]:
# Search index for multiple values
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
result2 = np.searchsorted(arr, [15, 25, 35])
print("[15, 25] should insert at:", result2, "index")


[10 20 30 40 50]
[15, 25] should insert at: [1 2 3] index


# SORTING

In [36]:
# SORT FUNCTION (1 Array-D)

import numpy as np
arr = np.array([40, 20, 50, 30, 10])
result = np.sort(arr)
print("Original Array:",arr)
print("Sorted array:", result)

# Sort the string
arr_str = np.array(['a', 'r', 's', 'h', 'a', 'd'])
str_result = np.sort(arr_str)
print("Sorted String:", str_result)

Original Array: [40 20 50 30 10]
Sorted array: [10 20 30 40 50]
Sorted String: ['a' 'a' 'd' 'h' 'r' 's']


In [40]:
# SORT FUNCTION (2-D Array)
# Row Wise (default)
import numpy as np
arr = np.array([
    [40, 20, 50],
    [30, 10, 40]
])
result = np.sort(arr)
print("Sorted array (Row wise):")
print(result)

# Column Wise 
import numpy as np
arr1 = np.array([
    [40, 20, 50],
    [30, 10, 40]
])
result1 = np.sort(arr1, axis=0)
print("Sorted array(Column wise):")
print(result1)

Sorted array (Row wise):
[[20 40 50]
 [10 30 40]]
Sorted array(Column wise):
[[30 10 40]
 [40 20 50]]


# FILTER FUNCTION

In [46]:
import numpy as np
age = np.array([45, 29, 12, 72, 31])
filter_arr = age > 25
print("Condition Check:",check_for_vote)
eligible_age = age[filter_arr]
print("Eligible Age:",eligible_age)

Condition Check: [ True  True False  True  True]
Eligible Age: [45 29 72 31]


In [47]:
# Without creating boolean variable
import numpy as np
age = np.array([45, 29, 12, 72, 31])
filter_arr = age[age > 25]
print("Eligible Age:",filter_arr)

Eligible Age: [45 29 72 31]


In [53]:
# Multiple filters (AND operator)
import numpy as np
age = np.array([45, 29, 12, 72, 31])
filter_arr1 = age[(age > 25) & (age < 50)]
print("Eligible Age:",filter_arr1)

# Multiple filters (or operator)
import numpy as np
age = np.array([45, 29, 12, 72, 31])
filter_arr1 = age[(age < 25) | (age > 50)]
print("Eligible Age:",filter_arr1)

Eligible Age: [45 29 31]
Eligible Age: [12 72]


# SHUFFLE FUNCTIONS

In [19]:
# 1-D Array
import numpy as np
arr = np.array([1, 2, 3, 4])
print("Before Shuffle:",arr)
np.random.shuffle(arr)
print("After Shuffle:",arr)
print()
# 2-D Array
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Before Shuffle:")
print(arr2d)
np.random.shuffle(arr2d)
print("After Shuffle:")
print(arr2d)

Before Shuffle: [1 2 3 4]
After Shuffle: [3 4 2 1]

Before Shuffle:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After Shuffle:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


# UNIQUE FUNCTIONS

In [31]:
# 1-D Array
import numpy as np
arr = np.array([1, 2, 3, 3, 2 , 1, 4, 4])
unique_data = np.unique(arr)
print("Original Array:", arr)
print("Unique Data:",unique_data)
print()

# Unique words in array (1-D Array)
str_arr = np.array(['Apple', 'Banana', 'Guava', 'Grapes', 'Apple', 'Banana'])
unique_str_data = np.unique(str_arr)
print("Original Array:", str_arr)
print("Unique Data:",unique_str_data)
print()

# 2-D Array
arr2d = np.array([
    [1, 2, 3, 3],
    [2 , 1, 4, 4]
])
unique_2D_data = np.unique(arr2d)
print("Original 2D Array:")
print(arr2d)
print("Unique 2D Data:")
print(unique_2D_data)
print()

# Get Unique Values and Their Counts
import numpy as np
arr_count = np.array([1, 2, 3, 3, 2 , 4])
unique_arr, count = np.unique(arr_count, return_counts=True)
print("Original Array:", arr)
print("Unique Array:",unique_arr)
print("Count:", count)
print()

# Get Unique Values and Their first occurance
arr_count = np.array([1, 3, 2 , 4])
unique_arr, fir_occ = np.unique(arr_count, return_index=True)
print("Original Array:", arr_count)
print("Unique Array:",unique_arr)
print("First Occurance Index:", fir_occ)

Original Array: [1 2 3 3 2 1 4 4]
Unique Data: [1 2 3 4]

Original Array: ['Apple' 'Banana' 'Guava' 'Grapes' 'Apple' 'Banana']
Unique Data: ['Apple' 'Banana' 'Grapes' 'Guava']

Original 2D Array:
[[1 2 3 3]
 [2 1 4 4]]
Unique 2D Data:
[1 2 3 4]

Original Array: [1 2 3 3 2 1 4 4]
Unique Array: [1 2 3 4]
Count: [1 2 2 1]

Original Array: [1 3 2 4]
Unique Array: [1 2 3 4]
First Occurance Index: [0 2 1 3]


# RESIZE FUNCTIONS

In [41]:
# Increase the 1D Array
import numpy as np
arr = np.array([1, 2, 3, 3, 2 ])
new_arr= np.resize(arr, (1, 7))
print("Original Array:", arr)
print("New Resized Data:", new_arr)
print()

# Decrease the 1D Array
arr = np.array([1, 2, 3, 3, 2 ])
new_arr= np.resize(arr, 3)
print("Original Array:", arr)
print("New Resized Data:", new_arr)
print()

# Resize a 1-D Array to a 2-D Array
arr = np.array([1, 2, 3, 3, 2 , 8])
new_2d_arr= np.resize(arr, (3, 3))
print("Original Array:", arr)
print("New Resized Data:")
print(new_2d_arr)
print()

Original Array: [1 2 3 3 2]
New Resized Data: [[1 2 3 3 2 1 2]]

Original Array: [1 2 3 3 2]
New Resized Data: [1 2 3]

Original Array: [1 2 3 3 2 8]
New Resized Data:
[[1 2 3]
 [3 2 8]
 [1 2 3]]



# FLATTEN & RAVEL FUNCTION

In [47]:
# Convert 2D array into 1D Array (Row Wise)
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original Array (Row wise):")
print(arr)
print()
print("2D array into 1D array:", arr.flatten())
print()

# Convert 2D array into 1D Array (Column Wise)
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original Array (Column wise):")
print(arr)
print()
print("2D array into 1D array:", arr.flatten(order='F'))
print()

Original Array (Row wise):
[[1 2 3]
 [4 5 6]]

2D array into 1D array: [1 2 3 4 5 6]

Original Array (Column wise):
[[1 2 3]
 [4 5 6]]

2D array into 1D array: [1 4 2 5 3 6]



# INSERT & DELETE

In [17]:
# INSERT
# 1-D Array
# Insert single element in 1-D array
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)
new_arr = np.insert(arr, 2, 100)
print("After Insert")
print(new_arr)
print()

# Insert multiple element in 1-D array
import numpy as np
arr_mul = np.array([1, 2, 3, 4])
print(arr_mul)
new_arr_mul = np.insert(arr_mul, 2, [100, 200, 300])
print("After Insert")
print(new_arr_mul)
print()

# Insert element at beginning in 1-D array
import numpy as np
arr_beg = np.array([1, 2, 3, 4])
print(arr_beg)
new_arr_beg = np.insert(arr_beg, 0, 100)
print("After Insert")
print(new_arr_beg)
print()

# Insert element at last in 1-D array
import numpy as np
arr_last = np.array([1, 2, 3, 4])
print(arr_last)
print("Lenght of array:", len(arr_last))
new_arr_last = np.insert(arr_last, len(arr_last), 100)
print("After Insert")
print(new_arr_last)
print()

# Insert element at last in 1-D array
import numpy as np
arr_mul_pos = np.array([1, 2, 3, 4])
print(arr_mul_pos)
new_arr_mul_pos = np.insert(arr_mul_pos, [0, 2, 4], 100)
print("After Insert")
print(new_arr_mul_pos)
print()

[1 2 3 4]
After Insert
[  1   2 100   3   4]

[1 2 3 4]
After Insert
[  1   2 100 200 300   3   4]

[1 2 3 4]
After Insert
[100   1   2   3   4]

[1 2 3 4]
Lenght of array: 4
After Insert
[  1   2   3   4 100]

[1 2 3 4]
After Insert
[100   1   2 100   3   4 100]



In [23]:
# 2-D Array
# Insert single element in 1-D array (Row wise (axis=0))
import numpy as np
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d)
new_arr2d = np.insert(arr2d, 1, [100, 200, 300], axis=0)
print("After Insert")
print(new_arr2d)
print()


# Insert single element in 1-D array (Column wise (axis=1))
import numpy as np
arr2d_col = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d_col)
new_arr2d_col = np.insert(arr2d_col, 1, [100, 200], axis=1)
print("After Insert")
print(new_arr2d_col)
print()

# Insert same element in 1-D array (Row wise (axis=0))
import numpy as np
arr2d_same_row = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d_same_row)
new_arr2d_same_row = np.insert(arr2d_same_row, 1, 100, axis=0)
print("After Insert")
print(new_arr2d_same_row)
print()

# Insert same element in 1-D array (Column wise (axis=1))
import numpy as np
arr2d_same_col = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d_same_col)
new_arr2d_same_col = np.insert(arr2d_same_col, 1, 10, axis=1)
print("After Insert")
print(new_arr2d_same_col)
print()

[[1 2 3]
 [4 5 6]]
After Insert
[[  1   2   3]
 [100 200 300]
 [  4   5   6]]

[[1 2 3]
 [4 5 6]]
After Insert
[[  1 100   2   3]
 [  4 200   5   6]]

[[1 2 3]
 [4 5 6]]
After Insert
[[  1   2   3]
 [100 100 100]
 [  4   5   6]]

[[1 2 3]
 [4 5 6]]
After Insert
[[ 1 10  2  3]
 [ 4 10  5  6]]



# APPEND METHOD

In [26]:
# 1-D Array
# Append single element in 1-D array
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)
new_arr = np.append(arr, 100)
print("After Insert")
print(new_arr)
print()

# Append Multiple element in 1-D array
import numpy as np
arr_mul = np.array([1, 2, 3, 4])
print(arr_mul)
new_arr_mul = np.append(arr_mul, [100, 200, 300])
print("After Insert")
print(new_arr_mul)
print()


[1 2 3 4]
After Insert
[  1   2   3   4 100]

[1 2 3 4]
After Insert
[  1   2   3   4 100 200 300]



In [34]:
# 2-D Array
# Append single element in 1-D array (Row wise (axis=0))
import numpy as np
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d)
new_arr2d = np.append(arr2d, [[100, 200, 300]], axis=0)
print("After Insert")
print(new_arr2d)
print()


# Append single element in 1-D array (Column wise (axis=1))
import numpy as np
arr2d_col = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d_col)
new_arr2d_col = np.append(arr2d_col, [[100], [200]], axis=1)
print("After Insert")
print(new_arr2d_col)
print()

[[1 2 3]
 [4 5 6]]
After Insert
[[  1   2   3]
 [  4   5   6]
 [100 200 300]]

[[1 2 3]
 [4 5 6]]
After Insert
[[  1   2   3 100]
 [  4   5   6 200]]



# DELETE METHOD

In [37]:
# 1-D Array
# Delete single element in 1-D array
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)
new_arr = np.delete(arr, 1)
print("After Insert")
print(new_arr)
print()

# Delete Multiple element in 1-D array
import numpy as np
arr_mul = np.array([1, 2, 3, 4])
print(arr_mul)
new_arr_mul = np.delete(arr_mul, [1, 2])
print("After Insert")
print(new_arr_mul)
print()

[1 2 3 4]
After Insert
[1 3 4]

[1 2 3 4]
After Insert
[1 4]



In [40]:
# 2-D Array
# Delete single row in 2-D array (Row wise (axis=0))
import numpy as np
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr2d)
new_arr2d = np.delete(arr2d, 1, axis=0)
print("After Insert")
print(new_arr2d)
print()


# Delete single column in 2-D array (Column wise (axis=1))
import numpy as np
arr2d_col = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d_col)
new_arr2d_col = np.delete(arr2d_col, 1, axis=1)
print("After Insert")
print(new_arr2d_col)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
After Insert
[[1 2 3]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]
After Insert
[[1 3]
 [4 6]]



# MATRIX

In [9]:
# Matrix using matric method
import numpy as np
matrix = np.matrix([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(matrix)
print("Types:", type(matrix))

[[1 2 3 4]
 [5 6 7 8]]
Types: <class 'numpy.matrix'>


In [10]:
# Matrix using array method
import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr)
print("Types:", type(arr))

[[1 2 3 4]
 [5 6 7 8]]
Types: <class 'numpy.ndarray'>


# Arithmatic operation in Numpy array and matrix

# Addition in Matrix

In [13]:
import numpy as np
matrix1 = np.matrix([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
matrix2 = np.matrix([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
add_res = matrix1 + matrix2
print(add_res)
print()


# Addition in Numpy array
import numpy as np
matrix11 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
matrix12 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
add_res2 = matrix11 + matrix12
print(add_res2)
print()

[[ 2  4  6  8]
 [10 12 14 16]]

[[ 2  4  6  8]
 [10 12 14 16]]



# Subtraction in Matrix

In [15]:
import numpy as np
matrix1 = np.matrix([
    [10, 20, 30, 40],
    [50, 60, 70, 80]
])
matrix2 = np.matrix([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
add_res = matrix1 - matrix2
print(add_res)
print()


# Subtraction in Numpy array
import numpy as np
matrix11 = np.matrix([
    [10, 20, 30, 40],
    [50, 60, 70, 80]
])
matrix12 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
add_res2 = matrix11 - matrix12
print(add_res2)
print()

[[ 9 18 27 36]
 [45 54 63 72]]

[[ 9 18 27 36]
 [45 54 63 72]]



# Multiplication in Matrix

In [24]:
import numpy as np
matrix1 = np.matrix([
    [10, 20],
    [50, 60]
])
matrix2 = np.matrix([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
add_res = matrix1 * matrix2
dot_add_res = matrix1.dot(matrix2)

print(add_res)
print()
print(dot_add_res)
print()




# Natrix Multiplication in Numpy array
import numpy as np
matrix11 = np.array([
    [10, 20],
    [50, 60]
])
matrix12 = np.array([
    [1, 2],
    [5, 6]
])
# add_res2 = matrix11 @ matrix12
add_res2 = np.matmul(matrix11, matrix12)
print(add_res2)
print()

[[110 140 170 200]
 [350 460 570 680]]

[[110 140 170 200]
 [350 460 570 680]]

[[110 140]
 [350 460]]



# MATRIX FUNCTIONS

# TRANSPOSE FUNCTION

In [3]:
# Transpose - using transpose() method
import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr)
print("Shape:",arr.shape)
print()
transpose_matrix = arr.transpose()
print(transpose_matrix)
print("Shape:",transpose_matrix.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Shape: (4, 2)


In [7]:
# Transpose - using .T method
import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr)
print("Shape:",arr.shape)
print()
transpose_matrix = arr.T
print(transpose_matrix)
print("Shape:",transpose_matrix.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Shape: (4, 2)


# SWAPAXES FUNCTION

In [9]:
# using swapaxes() method
import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr)
print("Shape:",arr.shape)
print()
swapaxes_arr = np.swapaxes(arr, 0, 1)
print(swapaxes_arr)
print("Shape:",swapaxes_arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Shape: (4, 2)


# INVERSE FUNCTION

In [15]:
# using np.linalg.inv() method
import numpy as np
arr = np.array([
    [4, 7],
    [2, 6]
])
print(arr)
print("Shape:",arr.shape)
print()
inverse_arr = np.linalg.inv(arr)
print(inverse_arr)

# Varify the inverse by multiplying arr * inverse_arr = identity matrix
varify_res = np.dot(arr, inverse_arr)
print(varify_res)
# Result is not identity matrix so that is not inverse

[[4 7]
 [2 6]]
Shape: (2, 2)

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]


# POWER FUNCTION

In [22]:
# using np.linalg.matrix_power() method - it is doing matrix multiplication not simple multiply
import numpy as np
arr = np.array([
    [4, 7],
    [2, 6]
])
print(arr)
print("Power 2: square matrix")
power2_arr = np.linalg.matrix_power(arr, 2)
print(power2_arr)
print("Power negetive: inverse matrix")
power_negetive_arr = np.linalg.matrix_power(arr, -1)
print(power_negetive_arr)
print("Power 0: Identity matrix")
power_zero_arr = np.linalg.matrix_power(arr, 0)
print(power_zero_arr)

[[4 7]
 [2 6]]
Power 2: square matrix
[[30 70]
 [20 50]]
Power negetive: inverse matrix
[[ 0.6 -0.7]
 [-0.2  0.4]]
Power 0: Identity matrix
[[1 0]
 [0 1]]


# DETERMINATE FUNCTION

In [24]:
# using np.linalg.det() method 
import numpy as np
arr = np.array([
    [4, 7],
    [2, 6]
])
print(arr)
print("Determinate value of matrix")
determinate_arr = np.linalg.det(arr)
print(determinate_arr)

[[4 7]
 [2 6]]
Determinate value of matrix
10.000000000000002
