# Numpy Fundamentals

In [16]:
# types of Numpy array
# 1. Scalar Array 0-D Array
import numpy as np
scalar_arr = np.array(2)
print("0-D Array -------")
print(scalar_arr)
print("Dimention:", scalar_arr.ndim)

# 2. 1-D Array
one_dim_arr = np.array([2, 4, 6, 8, 10])
print("1-D Array -----------")
print(one_dim_arr)
print("Dimention:", one_dim_arr.ndim)



# 3. 2-D Array
two_dim_arr = np.array([
            [1, 2, 3],
            [4, 5, 6]
])
print("2-D Array-----")
print(two_dim_arr)
print("Dimention:", two_dim_arr.ndim)




# 4. 3-D Array
three_dim_arr = np.array([[
            [1, 2],
            [4, 5]],

            [[11, 12],
            [14, 15]]                                
])
print("3-D Array-----")
print(three_dim_arr)
print("Dimention:", three_dim_arr.ndim)
print("Shape:", three_dim_arr.shape)


# 3. N-D Array
two_dim_arr = np.array([
            [1, 2, 3],
            [4, 5, 6]
])
print("2-D Array-----")
print(two_dim_arr)
print("Dimention:", two_dim_arr.ndim)

# 4. N-D Array
three_dim_arr = np.array([2, 3, 4, 5], ndmin=5)
print("N-D Array-----")
print(three_dim_arr)
print("Dimention:", three_dim_arr.ndim)
print("Shape:", three_dim_arr.shape)

0-D Array -------
2
Dimention: 0
1-D Array -----------
[ 2  4  6  8 10]
Dimention: 1
2-D Array-----
[[1 2 3]
 [4 5 6]]
Dimention: 2
3-D Array-----
[[[ 1  2]
  [ 4  5]]

 [[11 12]
  [14 15]]]
Dimention: 3
Shape: (2, 2, 2)
2-D Array-----
[[1 2 3]
 [4 5 6]]
Dimention: 2
N-D Array-----
[[[[[2 3 4 5]]]]]
Dimention: 5
Shape: (1, 1, 1, 1, 4)


In [18]:
# Take data from user than create numpy array
temp_data = []
for i in range(5):
    arr = int(input("Enter the Number: "))
    temp_data.append(arr)
print("Temp Data:", temp_data)
x = np.array(temp_data, ndmin=4)
print("Array:", x)
print("Type:", type(x))
print("Shape:", x.shape)
print("Dimension:", x.ndim)

Enter the Number:  1
Enter the Number:  2
Enter the Number:  3
Enter the Number:  4
Enter the Number:  5


Temp Data: [1, 2, 3, 4, 5]
Array: [[[[1 2 3 4 5]]]]
Type: <class 'numpy.ndarray'>
Shape: (1, 1, 1, 5)
Dimension: 4


<!-- DATA TYPES IN NUMPY ARRAY -->

DATA TYPES IN NUMPY ARRAY

In [49]:
# Boolean Data Types
import numpy as np
bool_data = np.array([True, False, False, True, True])
print("Boolean--------")
print(bool_data)
print("Data Type:",bool_data.dtype)

# Integer Data Types
import numpy as np
int_data = np.array([1, 2, 3, 4])
print("Integer--------")
print(int_data)
print("Data Type:",int_data.dtype)

# Float Data Types
import numpy as np
float_data = np.array([1.00, 2.33, 3.1, 4])
print("Float--------")
print(float_data)
print("Data Type:",float_data.dtype)

# Complex Data Types
import numpy as np
complex_data = np.array([2.02+3j, 2+7j, 3j, 4j])
print("Complex--------")
print(complex_data)
print("Data Type:",complex_data.dtype)


# String Data Types
import numpy as np
str_data = np.array(["Arshad", "Aatif", "Abhijeet", "Ashu"])
print("String--------")
print(str_data)
print("Data Type:",str_data.dtype)

# Data Type Conversion
# Float Data Types
import numpy as np
arr1 = [7, 8, 9.2, 10.87]
float_to_integer = np.array(arr1, dtype="f")
print("Data Type Conversion: Float to integer--------")
print(float_to_integer)
print("Data Type:",float_to_integer.dtype)


# How to use data-type as function
row_arr = np.array([3, 5, 7, 9])
float_func = np.float32(row_arr)
print("Data Type as Function--------")
print(float_func)
print("Data Type before conversion:",row_arr.dtype)
print("Data Type after conversion:",float_func.dtype)

# How to convert data-type without modifying original data - using astype method
row_arr = np.array([3, 5, 7, 9])
float_func = row_arr.astype("f")
print("Data Type as Function--------")
print(float_func)
print("Data Type before conversion:",row_arr.dtype)
print("Data Type after conversion:",float_func.dtype)

Boolean--------
[ True False False  True  True]
Data Type: bool
Integer--------
[1 2 3 4]
Data Type: int32
Float--------
[1.   2.33 3.1  4.  ]
Data Type: float64
Complex--------
[2.02+3.j 2.  +7.j 0.  +3.j 0.  +4.j]
Data Type: complex128
String--------
['Arshad' 'Aatif' 'Abhijeet' 'Ashu']
Data Type: <U8
Data Type Conversion: Float to integer--------
[ 7.    8.    9.2  10.87]
Data Type: float32
Data Type as Function--------
[3. 5. 7. 9.]
Data Type before conversion: int32
Data Type after conversion: float32
Data Type as Function--------
[3. 5. 7. 9.]
Data Type before conversion: int32
Data Type after conversion: float32


ARITHMATIC OPERATION IN NUMPY ARRAY

1-D ARRAY

In [77]:
# Addition:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])
add_sum = arr1 + arr2
print("Without Function")
print(add_sum)
print("Using Function")
func_add_sum = np.add(arr1 , arr2)
print(func_add_sum)
print()


# Subtraction:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])
diff = arr1 - arr2
print("Without Function")
print(diff)
print("using Function")
print(np.subtract(arr1, arr2))
print()


# Multiplication:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])
mul = arr1 * arr2
print("Without Function")
print(mul)
print("Using Function")
print(np.multiply(arr1, arr2))
print()


# Division:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])
div = arr1 / arr2
print("Without Function")
print(div)
print("using Function")
print(np.divide(arr1, arr2))
print()


# Modulus (Remainder):
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([3, 3, 3, 3])
mod = arr1 % arr2
print("Without Function")
print(mod)
print("using Function")
print(np.mod(arr1, arr2))
print()


# Exponential (Power):
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([3, 3, 3, 3])
exp = arr1 ** arr2
print("Without Function")
print(exp)
print("using Function")
print(np.power(arr1, arr2))

Without Function
[2 4 6 8]
Using Function
[2 4 6 8]

Without Function
[0 0 0 0]
using Function
[0 0 0 0]

Without Function
[ 1  4  9 16]
Using Function
[ 1  4  9 16]

Without Function
[1. 1. 1. 1.]
using Function
[1. 1. 1. 1.]

Without Function
[1 2 0 1]
using Function
[1 2 0 1]

Without Function
[ 1000  8000 27000 64000]
using Function
[ 1000  8000 27000 64000]


2-D ARRAY

In [92]:
# Addition:
import numpy as np
arr1 = np.array([
                    [1, 2],
                    [3, 4]
])
arr2 = np.array([
                    [10, 20],
                    [30, 40]
])
add_sum = arr1 + arr2
print("Addition - Without Function")
print(add_sum)
print("Using Function")
func_add_sum = np.add(arr1 , arr2)
print(func_add_sum)
print()


# Subtraction:
diff = arr1 - arr2
print("Subtraction - Without Function")
print(diff)
print("using Function")
print(np.subtract(arr1, arr2))
print()


# # Multiplication:
mul = arr1 * arr2
print("Multiplication - Without Function")
print(mul)
print("Using Function")
print(np.multiply(arr1, arr2))
print()


# Division:
div = arr1 / arr2
print("Division - Without Function")
print(div)
print("using Function")
print(np.divide(arr1, arr2))
print()


# Modulus (Remainder):
mod = arr1 % arr2
print("Modulus - Without Function")
print(mod)
print("using Function")
print(np.mod(arr1, arr2))
print()


# Exponential (Power):
exp = arr1 ** arr2
print("Exponential - Without Function")
print(exp)
print("using Function")
print(np.power(arr1, arr2))


# Reciprocal (1/a):
exp = 1 / arr1
print("Reciprocal - Without Function")
print(exp)
print("using Function")
print(np.reciprocal(arr1, arr2))

Addition - Without Function
[[11 22]
 [33 44]]
Using Function
[[11 22]
 [33 44]]

Subtraction - Without Function
[[ -9 -18]
 [-27 -36]]
using Function
[[ -9 -18]
 [-27 -36]]

Multiplication - Without Function
[[ 10  40]
 [ 90 160]]
Using Function
[[ 10  40]
 [ 90 160]]

Division - Without Function
[[0.1 0.1]
 [0.1 0.1]]
using Function
[[0.1 0.1]
 [0.1 0.1]]

Modulus - Without Function
[[1 2]
 [3 4]]
using Function
[[1 2]
 [3 4]]

Exponential - Without Function
[[          1     1048576]
 [-1010140999           0]]
using Function
[[          1     1048576]
 [-1010140999           0]]
Reciprocal - Without Function
[[1.         0.5       ]
 [0.33333333 0.25      ]]
using Function
[[1 0]
 [0 0]]


ARITHMATIC FUNCTIONS IN NUMPY ARRAY

In [99]:
# 1-D Array

# 1. Min & Max methods
import numpy as np
arr1 = np.array([7, 4, 6, 8, 11])
print(arr1)
print("Minimum element:", np.min(arr1))
print("Maximum element:", np.max(arr1))
print()
# 2. Position of Min & Max methods

import numpy as np

print("Position of Minimum element:", np.argmin(arr1))
print("Position of Maximum element:", np.argmax(arr1))
print()

[ 2  4  6  8 11]
Minimum element: 2
Maximum element: 11

Position of Minimum element: 0
Position of Maximum element: 4



In [108]:
# 2-D Array

# 1. Min & Max methods in 2-D Array
import numpy as np
arr2 = np.array(
    [
        [700, 40, 6],
        [10, 4, 80]
    ])
print(arr2)
print("Minimum element:", np.min(arr2))
print("Maximum element:", np.max(arr2))
print("Dimention:", arr2.ndim)
print("Shape:", arr2.shape)
print()

# 2. Position of Min & Max methods
print("Position of Minimum element:", np.argmin(arr2))
print("Position of Maximum element:", np.argmax(arr2))
print()

# Use of axis to find min and max (axis=1 - Row wise | axis=0 - Column wise)
print("Minimum element:", np.min(arr2, axis=1))
print("Position of Minimum element:", np.argmin(arr2, axis=1))
print("Maximum element:", np.max(arr2, axis=0))
print("Position of Maximum element:", np.argmax(arr2, axis=0))
print()
# Note: If we do not use axis than numpy conside all elements as 1D array

[[700  40   6]
 [ 10   4  80]]
Minimum element: 4
Maximum element: 700
Dimention: 2
Shape: (2, 3)

Position of Minimum element: 4
Position of Maximum element: 0

Minimum element: [6 4]
Position of Minimum element: [2 1]
Maximum element: [700  40  80]
Position of Maximum element: [0 0 1]



In [113]:
#  Square Root method in 1-D Array
import numpy as np
arr3 = np.array([9, 4, 16])
print(arr3)
print("1-D Array - Square Root:")
print(np.sqrt(arr3))

#  Square Root method in 2-D Array
import numpy as np
arr4 = np.array(
    [
        [9, 4, 16],
        [25,49, 36]
    ])
print(arr4)
print("2-D Array - Square Root:")
print(np.sqrt(arr4))


[ 9  4 16]
1-D Array - Square Root:
[3. 2. 4.]
[[ 9  4 16]
 [25 49 36]]
2-D Array - Square Root:
[[3. 2. 4.]
 [5. 7. 6.]]


In [117]:
# Sin and cos Value

# SIN Value
import numpy as np
arr5 = np.array([9, 4, 16])
print(arr5)
print("1-D Array - Sin value:")
print(np.sin(arr5))

#  Square Root method in 2-D Array
import numpy as np
arr6 = np.array(
    [
        [9, 4, 16],
        [25,49, 36]
    ])
print(arr6)
print("2-D Array - Sin:")
print(np.sin(arr6))
print()

# COS Value
arr6 = np.array([9, 4, 16])
print(arr6)
print("1-D Array - cos value:")
print(np.cos(arr6))

#  Cos value of elements in 2-D Array
import numpy as np
arr7 = np.array(
    [
        [9, 4, 16],
        [25,49, 36]
    ])
print(arr7)
print("2-D Array - cos:")
print(np.cos(arr7))
print()

[ 9  4 16]
1-D Array - Sin value:
[ 0.41211849 -0.7568025  -0.28790332]
[[ 9  4 16]
 [25 49 36]]
2-D Array - Sin:
[[ 0.41211849 -0.7568025  -0.28790332]
 [-0.13235175 -0.95375265 -0.99177885]]

[ 9  4 16]
1-D Array - cos value:
[-0.91113026 -0.65364362 -0.95765948]
[[ 9  4 16]
 [25 49 36]]
2-D Array - cos:
[[-0.91113026 -0.65364362 -0.95765948]
 [ 0.99120281  0.30059254 -0.12796369]]



In [120]:
# CUMSUM FUNCTION 

import numpy as np
arr7 = np.array([1, 2, 3])
print(arr7)
print("1-D Array - cumsum value:")
print(np.cumsum(arr7))

#  Cum Sum Values in 2-D Array
arr8 = np.array(
    [
        [9, 4, 16],
        [25,49, 36]
    ])
print(arr8)
print("2-D Array - cumsum value Row wise:")
print(np.cumsum(arr8, axis=1))
print("2-D Array - cumsum value Column wise:")
print(np.cumsum(arr8, axis=0))
print()

[1 2 3]
1-D Array - cumsum value:
[1 3 6]
[[ 9  4 16]
 [25 49 36]]
2-D Array - cumsum value Row wise:
[[  9  13  29]
 [ 25  74 110]]
2-D Array - cumsum value Column wise:
[[ 9  4 16]
 [34 53 52]]



RANDOM FUNCTIONS

In [123]:
# RAND FUNCTION
# 1-D Array
import numpy as np
rand1 = np.random.rand(4)
print(rand1)
print()

# 2-D Array
rand2 = np.random.rand(2, 4)
print(rand2)
print()

[0.0202167  0.53581893 0.44728299 0.35903615]

[[0.21486676 0.30633358 0.08110014 0.4676764 ]
 [0.18095688 0.53428631 0.21806264 0.39507993]]



In [125]:
# RANDN Fuction
# 1-D Array
import numpy as np
rand1 = np.random.randn(4)
print(rand1)
print()

# 2-D Array
rand2 = np.random.randn(2, 4)
print(rand2)
print()

[-0.85033977  0.92020921  0.54352803  0.95165459]

[[-1.5624589   0.08173797  0.51923385 -0.15756579]
 [-0.38689575  1.53600927  0.71216806 -0.79890554]]



In [127]:
# RANF FUNCTION
# 1-D Array
import numpy as np
rand1 = np.random.ranf(4)
print(rand1)
print()

# 2-D Array
rand2 = np.random.ranf((2, 4))
print(rand2)
print()

[0.28925664 0.3264367  0.89242197 0.03819911]

[[0.38357126 0.78991901 0.2840057  0.70709232]
 [0.83541576 0.58716482 0.86071266 0.26306984]]



In [150]:
# RANDINT  FUNCTION
# 1-D Array
# Number between 0 (default) to 4(excluded)
import numpy as np
rand1 = np.random.randint(10)
print(rand1)
print()

# Number between range ( start , end arguments )
rand2 = np.random.randint(2, 40)
print(rand2)
print()


# Generate 1-D Array of random numbers
rand3 = np.random.randint(2, 40, 3)
print(rand3)
print()


# 2D Array of Random Numbers
rand_2d = np.random.randint(3, 30, (3, 3))
print(rand_2d)

8

30

[12 22 15]

[[12 18 27]
 [19 14 18]
 [15  9 21]]


In [151]:
# SPECIAL TYPE OF NUMPY ARRAY

In [167]:
 # zeros() Function
# 1D Array
import numpy as np
zeros = np.zeros(5)
print("Zeros")
print(zeros)
# 2D Array
zeros_2d = np.zeros((3, 5))
print(zeros_2d)

# ones() Function
ones = np.ones(3)
print("Ones")
print(ones)
# 2D Array
ones_2d = np.ones((3, 5))
print(ones_2d)

# Empty() Function
empty = np.empty(4)
print("Empty")
print(empty)
# 2D Array
empty_2d = np.empty((3, 5))
print(empty_2d)

# Arange Function
arange = np.arange(5)
print("arange")
print(arange)
# 2D Array
arange_2d = np.arange(1, 11)
print(arange_2d)
arange_2d_step = np.arange(2, 11, 2)
print(arange_2d_step)

# Eye Function (Diagonal become 1's)
eye = np.eye(3)
print("eye")
print(eye)
# 2D Array
eye_2d = np.eye(1, 11)
print(eye_2d)
eye_2d_step = np.eye(2, 5)
print(eye_2d_step)


# Linespace Function 
linspace = np.linspace(3, 11, 10)
print("linspace")
print(linspace)
# Note: If we do not pass step than by default it take step=50

Zeros
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones
[1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Empty
[0.28925664 0.3264367  0.89242197 0.03819911]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
arange
[0 1 2 3 4]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
eye
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
linspace
[ 3.          3.88888889  4.77777778  5.66666667  6.55555556  7.44444444
  8.33333333  9.22222222 10.11111111 11.        ]


In [1]:
# NDITER Method for iteration

In [13]:
import numpy as np
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [4, 5, 6]
    ]
])
print("Dimension:", arr.ndim)
print("Shape:", arr.shape)
# Row wise iteration
for i in arr:
    print(i)
# Element wise iteration
print("Element wise iteration")
for i in arr:
    for j in i:
        for k in j:
            print(k)
# Element wise iteration using nditer method
print("Element wise iteration using nditer")
for i in np.nditer(arr):
    print(i)

Dimension: 3
Shape: (2, 2, 3)
[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [4 5 6]]
Element wise iteration
1
2
3
4
5
6
7
8
9
4
5
6
Element wise iteration using nditer
1
2
3
4
5
6
7
8
9
4
5
6


In [16]:
# flags & op_dtypes methods
# Convert the data type of the array during iteration 
import numpy as np
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [4, 5, 6]
    ]
])
print("Dimension:", arr.ndim , "|", "Shape:", arr.shape)
# Row wise iteration
for i in np.nditer(arr, flags=["buffered"], op_dtypes=["float"]):
    print(i)

Dimension: 3 | Shape: (2, 2, 3)
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
4.0
5.0
6.0


In [17]:
# ndenumerate methods
# Return the data along with its index of the array 
import numpy as np
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [4, 5, 6]
    ]
])
print("Dimension:", arr.ndim , "|", "Shape:", arr.shape)
# Row wise iteration
for index, value in np.ndenumerate(arr):
    print(index, value)

Dimension: 3 | Shape: (2, 2, 3)
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 4
(1, 1, 1) 5
(1, 1, 2) 6


In [25]:
# CONCATENATE VS STACK FUNCTION

# CONCATENATE
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print("Dimention", arr1.ndim, "|", "Shape", arr1.shape)
new_arr = np.concatenate((arr1, arr2))
print(new_arr)
print("Dimention", new_arr.ndim, "|", "Shape", new_arr.shape)
print()

# Stack
arr3 = np.array([1, 2, 3, 4])
arr4 = np.array([5, 6, 7, 8])
new_arr1 = np.stack((arr3, arr4))
print(new_arr1)
print("Dimention", new_arr1.ndim, "|", "Shape", new_arr1.shape)

Dimention 1 | Shape (4,)
[1 2 3 4 5 6 7 8]
Dimention 1 | Shape (8,)

[[1 2 3 4]
 [5 6 7 8]]
Dimention 2 | Shape (2, 4)


In [6]:
# SPLIT Method (divide in equal part)
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Dimention", arr1.ndim, "|", "Shape", arr1.shape)
new_arr = np.split(arr1, 3)
print(new_arr)
print()

# Array SPLIT Method (divide in equal & unequal part)
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Dimention", arr1.ndim, "|", "Shape", arr1.shape)
new_arr = np.array_split(arr1, 6)
print(new_arr)
print()


# Array SPLIT Method in 2D array (divide in equal & unequal part)
import numpy as np
arr2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print("Dimention", arr2d.ndim, "|", "Shape", arr2d.shape)
new_arr2d = np.array_split(arr2d, 3)
print(new_arr2d)
print()



# INDEXING
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Dimention", arr1.ndim, "|", "Shape", arr1.shape)
new_arr = np.array_split(arr1, 7)
print(new_arr)
print(new_arr[1])

Dimention 1 | Shape (9,)
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Dimention 1 | Shape (9,)
[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8]), array([9])]

Dimention 2 | Shape (2, 4)
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int32)]

Dimention 1 | Shape (9,)
[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7]), array([8]), array([9])]
[3 4]


In [25]:
# SEARCHING
import numpy as np
arr1 = np.array([1, 8, 3, 4, 5, 6, 7, 4, 8, 9])
print(f"Index of 4: {np.where(arr1==8)}")
print()

# Find the even number index
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 4, 8, 11])
print(f"Index of odd number: {np.where(arr1 % 2 != 0)}")
print()

# Find the index of number between 3 & 10 
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 11])
print(f"Index of number smaller than 3 & greater than 10: {np.where((arr2 < 3) | (arr2 > 10))}")
print()

# Searching in 2d array
import numpy as np
arr2d = np.array([
    [1, 2, 3, 4],
    [5, 4, 7, 8]
])
new_arr2d = np.where(arr2d % 2 == 0)
print("Greater than 2 in 2d array:",new_arr2d)
print()
# Note: It seperate the rows and columns

# Searching in 2d array - 
import numpy as np
arr2d_ = np.array([
    [1, 2, 3, 4],
    [5, 4, 7, 8]
])
row, column = np.where(arr2d_ % 2 == 0)
print("Greater than 2 in 2d array:")
print(row, column)

Index of 4: (array([1, 8], dtype=int64),)

Index of odd number: (array([0, 2, 4, 6, 9], dtype=int64),)

Index of number smaller than 3 & greater than 10: (array([ 0,  1, 10], dtype=int64),)

Greater than 2 in 2d array: (array([0, 0, 1, 1], dtype=int64), array([1, 3, 1, 3], dtype=int64))

Greater than 2 in 2d array:
[0 0 1 1] [1 3 1 3]


In [32]:
# Search sorted array
arr1 = np.array([1, 2, 3, 5, 6, 7])
print(f"Index to insert 4: {np.searchsorted(arr1, 4)}")
print()

# Search sorted array - Hnadling duplicate values using side
arr1 = np.array([1, 2, 2, 5, 6, 7])
print("Index to insert 2:", np.searchsorted(arr1, 2, side="left"))
print()

arr1 = np.array([1, 2, 2, 5, 6, 7])
print("Index to insert 2:", np.searchsorted(arr1, 2, side="right"))
print()

# Search multiple values
arr1 = np.array([1, 2, 3, 5, 6, 7])
print("Index to insert 2, 3 & 5:", np.searchsorted(arr1, [2, 3, 5]))
print()

Index to insert 4: 3

Index to insert 2: 1

Index to insert 2: 3

Index to insert 2, 3 & 5: [1 2 3]



In [38]:
# SORT FUNCTION
arr1 = np.array([10, 12, 2, 5, 16, 7, 1])
print("Sorted array", np.sort(arr1))
print()

# sort the string
arr_str = np.array(['a', 'r', 's', 'h', 'a', 'd'])
print("Sorted Characters:", np.sort(arr_str))
print()


# Sort in 2d array - row wise sorting (default)
import numpy as np
arr2d = np.array([
    [1, 5, 2, 4],
    [15, 14, 7, 8]
])
print("Sorted 2d array (Row wise):",np.sort(arr2d))
print()

# Sort in 2d array - Column wise sorting (axis=0)
import numpy as np
arr2dc = np.array([
    [11, 15, 12, 4],
    [15, 14, 7, 8]
])
print("Sorted 2d array(Column wise):",np.sort(arr2dc, axis=0))
print()

Sorted array [ 1  2  5  7 10 12 16]

Sorted Characters: ['a' 'a' 'd' 'h' 'r' 's']

Sorted 2d array (Row wise): [[ 1  2  4  5]
 [ 7  8 14 15]]

Sorted 2d array(Column wise): [[11 14  7  4]
 [15 15 12  8]]



In [64]:
# FILTER FUNCTION
# Single Condition
import numpy as np
age = np.array([21, 45, 12, 24, 56, 11, 55])
filter_age = age > 18
print("eligible age for voting:")
print(age[filter_age])
print()

# Multiple Condition
import numpy as np
new_age = np.array([2, 45, 12, 24, 56, 18, 55])
new_filter_age = new_age[(new_age > 18) | (new_age == 18)]
print("eligible age for voting:")
print(new_filter_age)

eligible age for voting:
[21 45 24 56 55]

eligible age for voting:
[45 24 56 18 55]


In [77]:
# SHUFFLE/RANDOM FUNCTION

# Shuffle 1D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Before Shuffle:", arr)
np.random.shuffle(arr)
print("After Shuffle:", arr)
print()

# Shuffle 2D array
import numpy as np
arr2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 3, 45, 67]
])
print("Before Shuffle:")
print(arr2d)
np.random.shuffle(arr2d)
print("After Shuffle:")
print(arr2d)


Before Shuffle: [1 2 3 4 5]
After Shuffle: [4 3 5 2 1]

Before Shuffle:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  3 45 67]]
After Shuffle:
[[11 12  3 45 67]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [87]:
# UNIQUE FUNCTIONS
# Unique Function - in numbers
import numpy as np
arr = np.array([1, 2, 3, 4, 4, 3, 5])
print("Original array:", arr)
print("Unique array:", np.unique(arr))

# Unique Function - in string
import numpy as np
arr_str = np.array(["Apple", "Apple", "Banana", "Grapes", "Banana"])
print("Original array:", arr_str)
print("Unique array:", np.unique(arr_str))


# Unique Function - in 2d array
import numpy as np
arr_2d = np.array([
    [1, 2, 1, 2, 3],
    [3, 4, 5, 4, 3]
])
print("Original array:", arr_2d)
print("Unique array:", np.unique(arr_2d))
print()

# Unique Function - get unique values and their counts
import numpy as np
arr = np.array([1, 2, 3, 4, 4, 3, 5])
print("Original array:", arr)
unique, counts = np.unique(arr, return_counts=True)
print("Unique array:",unique)
print("Counts:",counts)
print()

# Unique Function - get unique values and their index
import numpy as np
arr = np.array([11, 2, 3, 4, 4, 3, 5])
print("Original array:", arr)
unique, index = np.unique(arr, return_index=True)
print("Unique array:",unique)
print("index:",index)

Original array: [1 2 3 4 4 3 5]
Unique array: [1 2 3 4 5]
Original array: ['Apple' 'Apple' 'Banana' 'Grapes' 'Banana']
Unique array: ['Apple' 'Banana' 'Grapes']
Original array: [[1 2 1 2 3]
 [3 4 5 4 3]]
Unique array: [1 2 3 4 5]

Original array: [1 2 3 4 4 3 5]
Unique array: [1 2 3 4 5]
Counts: [1 1 2 2 1]

Original array: [11  2  3  4  4  3  5]
Unique array: [ 2  3  4  5 11]
index: [1 2 3 6 0]


In [7]:
# RESIZE FUNCTIONS 
# 1D array into 2D array
import numpy as np
arr = np.array([1, 4, 2, 6, 3, 9])
print("Dimension:", arr.ndim, "| Shape:", arr.shape)
resized_arr = np.resize(arr, (3, 4))
print(resized_arr)
print("Resized Dimension:", resized_arr.ndim, "| Resize Shape:", resized_arr.shape)
print()

# 3D array into 1D array
import numpy as np
arr3d = np.array([
    [
        [1, 4, 2],
        [2, 3, 4]
    ],
    [
        [2, 5, 7],
        [6, 8, 1]
    ]
])
print(arr3d)
print("Dimension:", arr3d.ndim, "| Shape:", arr3d.shape)
resized_arr3d = np.resize(arr, (8,))
print(resized_arr3d)
print("Resized Dimension:", resized_arr3d.ndim, "| Resize Shape:", resized_arr3d.shape)


Dimension: 1 | Shape: (6,)
[[1 4 2 6]
 [3 9 1 4]
 [2 6 3 9]]
Resized Dimension: 2 | Resize Shape: (3, 4)

[[[1 4 2]
  [2 3 4]]

 [[2 5 7]
  [6 8 1]]]
Dimension: 3 | Shape: (2, 2, 3)
[1 4 2 6 3 9 1 4]
Resized Dimension: 1 | Resize Shape: (8,)


In [24]:
# INSERT FUNCTION
# Insert single element
import numpy as np
arr = np.array([1, 2, 3, 4, 6])
print(arr)
print("After Insert:", np.insert(arr, 4, 5))
print()

# Insert multiple element
import numpy as np
arr1 = np.array([1, 2, 3, 4, 10])
print(arr1)
print("After Insert(multiple elements):", np.insert(arr1, 4, [5, 6, 7]))
print()

# Insert multiple element at multiple different index
import numpy as np
arr2 = np.array([1, 3, 5, 7])
print(arr2)
print("After Insert(multiple elements at multiple index):", np.insert(arr2, [1,2, 3], [2, 4, 6]))
print()

# Insert element at beginning
import numpy as np
arr3 = np.array([1, 3, 5, 7])
print(arr3)
print("After Insert(at beginning):", np.insert(arr3, 0, 100))
print()

# Insert element at last
import numpy as np
arr3 = np.array([1, 3, 5, 7])
print(arr3)
print("After Insert(at last):", np.insert(arr3, len(arr3), 101))
print()

# Insert single element at multiple position
import numpy as np
arr4 = np.array([1, 3, 5, 7])
print(arr4)
print("After Insert(at last):", np.insert(arr4, [0, 1, 2, len(arr4)], 99))
print()

[1 2 3 4 6]
After Insert: [1 2 3 4 5 6]

[ 1  2  3  4 10]
After Insert(multiple elements): [ 1  2  3  4  5  6  7 10]

[1 3 5 7]
After Insert(multiple elements at multiple index): [1 2 3 4 5 6 7]

[1 3 5 7]
After Insert(at beginning): [100   1   3   5   7]

[1 3 5 7]
After Insert(at last): [  1   3   5   7 101]

[1 3 5 7]
After Insert(at last): [99  1 99  3 99  5  7 99]



In [40]:
# Insert into 2D array
# Row wise(axis=0)
import numpy as np
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d)
print("After Inserted(Row wise):\n", np.insert(arr2d, 1, [100, 100, 100], axis=0))
print()

# Insert same elements - Row wise(axis=0)
import numpy as np
arr2dsame = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2dsame)
print("After Inserted(Row wise):\n", np.insert(arr2dsame, 1, 99, axis=0))
print()

# Column wise(axis=1)
import numpy as np
arr2dcol = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2dcol)
print("After Inserted(Column wise):\n", np.insert(arr2d, 1, [111, 111], axis=1))
print()

# Insert same elements - Column wise(axis=1)
import numpy as np
arr2dcolumn = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2dcolumn)
print("After Inserted(Row wise):\n", np.insert(arr2dcolumn, 1, 99, axis=1))
print()

[[1 2 3]
 [4 5 6]]
After Inserted(Row wise):
 [[  1   2   3]
 [100 100 100]
 [  4   5   6]]

[[1 2 3]
 [4 5 6]]
After Inserted(Row wise):
 [[ 1  2  3]
 [99 99 99]
 [ 4  5  6]]

[[1 2 3]
 [4 5 6]]
After Inserted(Column wise):
 [[  1 111   2   3]
 [  4 111   5   6]]

[[1 2 3]
 [4 5 6]]
After Inserted(Row wise):
 [[ 1 99  2  3]
 [ 4 99  5  6]]



In [55]:
# APPEND METHOD
# It insert elements at last index
# Append in 1D array
import numpy as np
arr = np.array([1, 2, 3, 4])
print("Original Array:", arr)
print("After Append (1D):", np.append(arr, 100))
print()

# Append multiple elements
import numpy as np
arr = np.array([1, 2, 3, 4])
print("Original Array:", arr)
print("After Append (1D):", np.append(arr, [100, 200, 300]))
print()

# Append in 2D array - Row wise (axis=0)
import numpy as np
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print("Original Array:", arr2)
print("After Append(2D-Row wise)\n", np.append(arr2, [[100, 200, 300, 400]], axis=0))
print()

# Append in 2D array - Column wise (axis=1)
import numpy as np
arr2c = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print("Original Array\n", arr2c)
print("After Append(2D-column wise)\n", np.append(arr2c, [[100], [200]], axis=1))

Original Array: [1 2 3 4]
After Append (1D): [  1   2   3   4 100]

Original Array: [1 2 3 4]
After Append (1D): [  1   2   3   4 100 200 300]

Original Array: [[1 2 3 4]
 [5 6 7 8]]
After Append(2D-Row wise)
 [[  1   2   3   4]
 [  5   6   7   8]
 [100 200 300 400]]

Original Array
 [[1 2 3 4]
 [5 6 7 8]]
After Append(2D-column wise)
 [[  1   2   3   4 100]
 [  5   6   7   8 200]]


In [59]:
# DELETE FUNCTION
# Delete single element in 1D Array
import numpy as np
arr = np.array([1, 2, 3, 4])
print("Original Array:", arr)
print("After Delete (1D):", np.delete(arr, 1))
print()

# Delete multiple elements in 1D Array
import numpy as np
arrM = np.array([1, 2, 3, 4])
print("Original Array:", arrM)
print("After Delete (1D):", np.delete(arrM, [1, 3]))
print()


# DELETE in 2D Array - Row wise (axis=0)
import numpy as np
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Original Array:", arr2)
print("After Delete(2D-Row wise)\n", np.delete(arr2, 1, axis=0))
print()


# DELETE in 2D Array - Column wise (axis=1)
import numpy as np
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Original Array:", arr2)
print("After Delete(2D-Row wise)\n", np.delete(arr2, 1, axis=1))
print()

Original Array: [1 2 3 4]
After Delete (1D): [1 3 4]

Original Array: [1 2 3 4]
After Delete (1D): [1 3]

Original Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After Delete(2D-Row wise)
 [[ 1  2  3  4]
 [ 9 10 11 12]]

Original Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After Delete(2D-Row wise)
 [[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]



In [61]:
# MATRIX METHOD
import numpy as np
matrix1 = np.matrix([
    [1, 2, 3],
    [4, 5, 6]
])
print(matrix1)
print("Dimension:", matrix1.ndim, "| Shape:", matrix1.shape)
print("Type:", type(matrix1))

[[1 2 3]
 [4 5 6]]
Dimension: 2 | Shape: (2, 3)
Type: <class 'numpy.matrix'>


In [71]:
# multiplication in Numpy array
import numpy as np
arr1 = np.array([
    [1, 2],
    [4, 5]
])
arr2 = np.array([
    [1, 2],
    [4, 5]
])
print("Multiplication in numpy array\n",arr1 * arr2)
print()


# Matrix multiplication in numpy array - using @ operator
import numpy as np
arr1 = np.array([
    [1, 2],
    [4, 5]
])
arr2 = np.array([
    [1, 2],
    [4, 5]
])
print("Matrix Multiplication in numpy array (@ operator)\n",arr1 @ arr2)
print()

# Matrix multiplication in numpy array - using matmul() function
import numpy as np
arr1 = np.array([
    [1, 2],
    [4, 5]
])
arr2 = np.array([
    [1, 2],
    [4, 5]
])
print("Matrix Multiplication in numpy array(matmul function)\n",np.matmul(arr1 ,arr2))
print()

Multiplication in numpy array
 [[ 1  4]
 [16 25]]

Multiplication in Matrix
 [[ 9 12]
 [24 33]]

Matrix Multiplication in numpy array (@ operator)
 [[ 9 12]
 [24 33]]

Matrix Multiplication in numpy array(matmul function)
 [[ 9 12]
 [24 33]]



In [73]:
# MATRIX MULTIPLICATION
# Using * operator
import numpy as np
mat1 = np.matrix([
    [1, 2],
    [4, 5]
])
mat2 = np.matrix([
    [1, 2],
    [4, 5]
])
print("Multiplication in Matrix (using * operator)\n",mat1 * mat2)
print()

# Using dot() function
import numpy as np
mat3 = np.matrix([
    [1, 2],
    [4, 5]
])
mat4 = np.matrix([
    [1, 2],
    [4, 5]
])
print("Multiplication in Matrix (using dot function )\n",mat3.dot(mat4))
print()

Multiplication in Matrix (using * operator)
 [[ 9 12]
 [24 33]]

Multiplication in Matrix (using dot function )
 [[ 9 12]
 [24 33]]



In [87]:
# MATRIX FUNCTIONS
# Transpose method (transpose())
import numpy as np
arr1 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr1)
print("Dimension:", arr1.ndim, "| Shape:", arr1.shape)

# trans = np.transpose(arr1) 
# or
trans = arr1.T

print("Convert Rows into columns and col in rows\n",trans)
print("Dimension:", trans.ndim, "| Shape:", trans.shape)


[[1 2 3 4]
 [5 6 7 8]]
Dimension: 2 | Shape: (2, 4)
Convert Rows into columns and col in rows
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
Dimension: 2 | Shape: (4, 2)


In [91]:
# SWAPAXES Method
import numpy as np
arr1 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr1)
print("Dimension:", arr1.ndim, "| Shape:", arr1.shape)
swap = np.swapaxes(arr1, 1, 0)
print("Swapped Axes:\n", swap)
print("Dimension:", trans.ndim, "| Shape:", trans.shape)
# Note: it worked like transpose method

[[1 2 3 4]
 [5 6 7 8]]
Dimension: 2 | Shape: (2, 4)
Swapped Axes:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
Dimension: 2 | Shape: (4, 2)


In [100]:
# Inverse matrix function
# Rule: A * A^-1 = I
import numpy as np
arr = np.matrix([
    [1, 3],
    [4, 5]
])
print(arr)
inverse_mat = np.linalg.inv(arr)
print("Inverse matrix: \n", inverse_mat)

# Varify inverse_mat matrix is inverse of arr matrix
res = arr * inverse_mat
print("Result:\n", res)

# [-0.7   0.4]
# [0.5    0.14

[[1 3]
 [4 5]]
Inverse matrix: 
 [[-0.71428571  0.42857143]
 [ 0.57142857 -0.14285714]]
Result:
 [[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [107]:
# Power in matrix - matrix multiplication with same matrix
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)
print()

# Power integer - like squre, cube
square_matrix = np.linalg.matrix_power(arr, 2)
print("Square of the matrix:\n", square_matrix)
print()

# Power Zero - identity matrix
zero_power_matrix = np.linalg.matrix_power(arr, 0)
print("0 power of the matrix:\n", zero_power_matrix)
print()

# Power negetive - inverse matrix
neg_power_matrix = np.linalg.matrix_power(arr, -1)
print("Negetive power of the matrix:\n", neg_power_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Square of the matrix:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

0 power of the matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

Negetive power of the matrix:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [113]:
# Determinate of matrix -> det(A) = ad-bc
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)
det = np.linalg.det(arr)
print("Determinante:\n", det)
# -3-2(-6)+3(-3) = -3+12-9=0

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinante:
 -9.51619735392994e-16
